version : '3.8'


services:
  postgres:
    container_name: find-a-friend-api
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=find-a-friend
      - PG_DATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
